#!/usr/bin/env python3
"""
Cleanup script to delete all API-generated segments from MoEngage
This script will find and delete segments that match the naming patterns used by the automation
"""

import requests
import json
import base64
from datetime import datetime

# MoEngage API Configuration
WORKSPACE_ID = "95PNUHBSYSLLJZ22PEOFMKF2"
DATA_API_KEY = "Mj5JSGKcwYum9NKAGmGHJG_E"
DATA_CENTER = "01"
BASE_URL = f"https://api-{DATA_CENTER}.moengage.com/v3"

def get_all_segments():
    """Get all segments from MoEngage"""
    url = f"{BASE_URL}/custom-segments"
    
    # Auth
    auth_string = f"{WORKSPACE_ID}:{DATA_API_KEY}"
    encoded_auth = base64.b64encode(auth_string.encode()).decode()
    
    headers = {
        'Authorization': f'Basic {encoded_auth}',
        'Content-Type': 'application/json',
        'MOE-APPKEY': WORKSPACE_ID
    }
    
    try:
        response = requests.get(url, headers=headers, timeout=15)
        print(f"Response status: {response.status_code}")
        if response.status_code == 200:
            data = response.json()
            print(f"Response type: {type(data)}")
            print(f"Response keys: {data.keys() if isinstance(data, dict) else 'Not a dict'}")
            
            # Handle different response structures
            if isinstance(data, dict):
                if 'data' in data:
                    segments_data = data['data']
                    if isinstance(segments_data, dict) and 'custom_segments' in segments_data:
                        return segments_data['custom_segments']
                    elif isinstance(segments_data, list):
                        return segments_data
                    else:
                        return []
                else:
                    # Maybe segments are directly in the response
                    return data.get('custom_segments', [])
            elif isinstance(data, list):
                return data
            else:
                print(f"Unexpected response format: {type(data)}")
                return []
        else:
            print(f"Error fetching segments: {response.status_code} - {response.text}")
            return []
    except Exception as e:
        print(f"Exception fetching segments: {e}")
        import traceback
        traceback.print_exc()
        return []

def delete_segment(segment_id):
    """Delete a specific segment"""
    url = f"{BASE_URL}/custom-segments/{segment_id}"
    
    # Auth
    auth_string = f"{WORKSPACE_ID}:{DATA_API_KEY}"
    encoded_auth = base64.b64encode(auth_string.encode()).decode()
    
    headers = {
        'Authorization': f'Basic {encoded_auth}',
        'Content-Type': 'application/json',
        'MOE-APPKEY': WORKSPACE_ID
    }
    
    try:
        response = requests.delete(url, headers=headers, timeout=15)
        return {
            'success': response.status_code in [200, 204],
            'status_code': response.status_code,
            'message': response.text if response.status_code not in [200, 204] else 'Deleted successfully'
        }
    except Exception as e:
        return {
            'success': False,
            'status_code': 0,
            'message': str(e)
        }

def is_api_generated_segment(segment_name):
    """Check if segment was generated by our API automation"""
    api_patterns = [
        'UK_All_Users',
        'UAE_All_Users', 
        'UK_Active_Users',
        'UAE_Active_Users',
        'UK_Received_Push',
        'UAE_Received_Push',
        'UK_Received_Email', 
        'UAE_Received_Email',
        'UK_Active_Received_Push',
        'UAE_Active_Received_Push',
        'UK_Active_Received_Email',
        'UAE_Active_Received_Email',
        'UK_Unsubscribed_Push',
        'UAE_Unsubscribed_Push',
        'UK_Unsubscribed_Email',
        'UAE_Unsubscribed_Email',
        # Legacy patterns with timestamps
        'Metrics_GB_',
        'Metrics_AE_',
        'UK_All_Users_',
        'UAE_All_Users_',
        'UK_Active_Users_',
        'UAE_Active_Users_',
        'UK_Received_Push_',
        'UAE_Received_Push_',
        'UK_Received_Email_',
        'UAE_Received_Email_',
        'UK_Active_Received_Push_',
        'UAE_Active_Received_Push_',
        'UK_Active_Received_Email_',
        'UAE_Active_Received_Email_',
        'UK_Unsubscribed_Push_',
        'UAE_Unsubscribed_Push_',
        'UK_Unsubscribed_Email_',
        'UAE_Unsubscribed_Email_'
    ]
    
    return any(segment_name.startswith(pattern) for pattern in api_patterns)

def main():
    """Main cleanup function"""
    print("🧹 MoEngage Segment Cleanup Tool")
    print("=" * 50)
    
    # Get all segments
    print("📋 Fetching all segments...")
    segments = get_all_segments()
    
    if not segments:
        print("❌ No segments found or error fetching segments")
        return
    
    print(f"📊 Found {len(segments)} total segments")
    
    # Filter API-generated segments
    api_segments = []
    for segment in segments:
        if is_api_generated_segment(segment.get('name', '')):
            api_segments.append(segment)
    
    if not api_segments:
        print("✅ No API-generated segments found to clean up")
        return
    
    print(f"🎯 Found {len(api_segments)} API-generated segments to clean up:")
    for segment in api_segments:
        print(f"  - {segment.get('name', 'Unknown')} (ID: {segment.get('id', 'Unknown')})")
    
    # Confirm deletion
    confirm = input(f"\n⚠️  Are you sure you want to delete {len(api_segments)} segments? (yes/no): ").lower().strip()
    
    if confirm != 'yes':
        print("❌ Cleanup cancelled")
        return
    
    # Delete segments
    print(f"\n🗑️  Deleting {len(api_segments)} segments...")
    successful_deletions = 0
    failed_deletions = 0
    
    for segment in api_segments:
        segment_id = segment.get('id')
        segment_name = segment.get('name', 'Unknown')
        
        if not segment_id:
            print(f"❌ Skipping {segment_name} - no ID found")
            failed_deletions += 1
            continue
        
        print(f"🗑️  Deleting: {segment_name}...")
        result = delete_segment(segment_id)
        
        if result['success']:
            print(f"✅ Deleted: {segment_name}")
            successful_deletions += 1
        else:
            print(f"❌ Failed to delete {segment_name}: Status {result['status_code']} - {result['message']}")
            failed_deletions += 1
    
    # Summary
    print("\n" + "=" * 50)
    print("📊 Cleanup Summary:")
    print(f"✅ Successfully deleted: {successful_deletions} segments")
    print(f"❌ Failed to delete: {failed_deletions} segments")
    print(f"📊 Total processed: {len(api_segments)} segments")
    
    if successful_deletions > 0:
        print("🎉 Cleanup completed successfully!")
    else:
        print("⚠️  No segments were deleted")

if __name__ == "__main__":
    main()